### ISSUE TITLE
Sync with OpenTasks does not work anymore

### ISSUE THREAD

**Issue by Sighisorean** [etesync/android#231] opened 2023-06-22 11:31 UTC
I realized that syncing with OpenTasks does not work any ore showing this:
"* Aufgaben werden nicht synchronisiert (installieren Sie einen Anbieter)."

EteSync is set up to use OpenTasks, not Tasks.org. Both task-apss are installed. Everything works fine for months.

I already tried some things, even uninstalling OpenTasks and EteSync and installing and setup again but the error persists.

**Comment by tasn** [comment] 2023-06-22 12:02
Sounds like a duplicate of https://github.com/etesync/android/issues/226 ?
Updating to 2.4.1 or downgrading to 2.3 should fix it. Let me know if that's not the case and I'll reopen the ticket.

**Closed by tasn** 2023-06-22 12:02 UTC

**Comment by tasn** [comment] 2023-06-22 13:11
It'll be hopefully relesaed on f-droid in the next couple of days. You can revert to 2.3 until they finish building it.
