### ISSUE TITLE
Impossible te remove the "delete the logs" notification

### ISSUE THREAD

**Issue by guy-teube** [etesync/android#23] opened 2018-01-02 18:03 UTC
Hello again, 

Question relative to the [previous one](https://github.com/etesync/android/issues/22).

I have the notification "EteSync file logging - /path/to/log.file - Supprimer les journaux dès que possible"

I  have deleted manually all the log files. But the notification is still here. Impossible to swap it, tap on it makes nothing.
So, how to remove it, without wait the next reboot of the mobile (kill the Etesync app doesn't hide the notification) ?

Thank you

**Comment by tasn** [comment] 2018-01-02 18:12
Hey,

It's by design. As long as you are logging to file, it'll stay there because logs may contain sensitive information so it's a reminder do delete them.

In order to get rid of the notification you just need to turn off logging to file from the settings.

I'm closing this issue, but please reopen if the above suggestion doesn't work.

--
Tom.

**Comment by guy-teube** [comment] 2018-01-02 18:37
Okay.

Maybe a tap on the notif could open the parameter window, to make this behavior more understandable.

**Comment by tasn** [comment] 2018-01-02 18:39
Fair point, reopening, and will find a way to make it more obvious.

**Closed** 2018-01-17 14:25 UTC
