### ISSUE TITLE
opt out on calendars to sync

### ISSUE THREAD

**Issue by Zybque** [etesync/android#153] opened 2020-11-15 04:53 UTC
I would like the option to not-sync certain collections on some devices. I know dav5x has this option, a simple opt-out checkbox. It's not vital but It would help me keep my focus.

**Comment by tasn** [comment] 2020-11-15 07:36
Thanks for reporting! I'm closing it because it's a duplicate of #48. Please let's continue the discussion there.

**Closed by tasn** 2020-11-15 07:36 UTC
