### ISSUE TITLE
Not syncing contacts on Oneplus One after importing from google

### ISSUE THREAD

**Issue by guandalf** [etesync/android#24] opened 2018-01-21 10:02 UTC
Hi,

etesync is not syncing contacts after import from a google account.
It imports 574 contacts but journal entries are always 0 and after importing the entries keep increasing every time I check the contacts account.
I'm on a Oneplus one with a custom rom (Tugapower, some LineageOS 14.1).

Calendar works, imported from same account.

Help because it's not usable at all like this (and the trial expires in 13 days :)

Thank you.

**Comment by tasn** [comment] 2018-01-21 12:59
Hi,

Sorry to hear about your issue, but don't worry, we'll figure it out.

First of all, as a temporary workaround, consider exporting your address book to a file, and then importing it from file. You can export to file directly from the lineageos address book app, and import from the etesync app (or maybe even from the address book app, never tried this path).
This should hopefully/potentially fix it for you for now. You may also need to reinstall the etesync app before you do it just to stop the importing of contacts to happen more and more.

As for the issue at hand:
What exactly do you get when you do import? Does it popup a progress dialog saying it's importing? If so, does it ever finish? Show a dialog saying it finished? Failed?
Could you please also send the content of "Settings -> Debug info" to us by email? Address is available here: https://www.etesync.com/about/#contact
If the workaround works but you'd still like to test import so we can reproduce the failure, you can create a new test journal, and try importing to it instead of to your main one. This way, once we are done testing, you can just delete it.
Once you provide answers to the questions above, we can try to better debug it.

Don't worry about your trial, we'll extend it until this is resolved, though I hope we'll resolve it long before it's even needed.

Thanks for reporting!

**Comment by guandalf** [comment] 2018-01-21 19:32
I'm sorry but importing from a file, exported from the contacts app, works even worse. It actually never moves away from the dialog saying "importing 1/100" and only killing the app gives it me back.

Going back to importing from the google account, I get the dialog that shows the progress, and I see the importing proceeding to the number of actual records minus one, than that dialog closes and I get back to the list of the account to choose from when importing, without getting any feedback on the operation.
I also tried to create new journals several times but the issue remains on all of them.

I attached the debug info as requested.

Thank you very much for your help.

Regards.

[debug.txt](https://github.com/etesync/android/files/1650117/debug.txt)

**Comment by tasn** [comment] 2018-01-21 21:28
Thanks for the info. I edited your comment to remove the link to the debug info. It doesn't really contain any secret information, but still, better to not have it shared.

The next version of EteSync will have a built-in error catching and reporting facility, it's not yet released, but here is a version for you to install: [next etesync apk](https://stosb.com/~tom/app-release.apk)
It's signed using the same key as the Google play release, so it should **not** complain about a mismatching signature. If it does, it means the apk has been tampered with, and you should not install it.

Have you deleted the default address books and calendars, or did you just never have ones pre-set?
From the settings, could you please enable logging to file, and then try to import from file again?
Please send this one by email, as it may also contain private information.
Could you also try importing from account again with the new apk linked to above? It should bring up a stack trace and let you send it to me by email.

Thanks.

**Comment by guandalf** [comment] 2018-01-22 11:04
Hi, something changed with the new revision and now I have the app importing a number of entries but this number is different from the one I get both in Contacts and in Journal Entries.

Anyway I'm packing and sending you the log files via email.

Thank you for the trial period extension! :)

**Comment by tasn** [comment] 2018-01-22 11:15
Thanks, and of course. No worries. Sorry again for the issues.

**Comment by tasn** [comment] 2018-01-22 12:29
Just for reference: I searched my old emails and I found another user who reported a similar issue.
He's using a vanilla Samsung, so a different ROM. This is an interesting find, because it means it may be a content issue (i.e a contact type/property that we don't handle correctly) rather than a ROM issue.

I'm at the process of updating some of our dependencies, including the contact handling library, I wonder if it's an issue that was fixed there. Will update as I go.

**Comment by tasn** [comment] 2018-01-24 22:56
Mostly fixed in v0.2.0 with
536bef9815555487fe03edf42302db6c39b5522f

Though also fixed with:
2f1a9281b868421f00da1e9635e97e3f6440ace1
and
5a2f8260c7d2b9827187f19a3db9a43e9e922a3e

Which will be included in the next release.

There's more info in the commit message about the issue.

**Closed by tasn** 2018-01-24 22:56 UTC
