### ISSUE TITLE
app doesn't show tasklist journal if it was created from tasks.org

### ISSUE THREAD

**Issue by acthp** [etesync/android#105] opened 2020-02-10 18:16 UTC
Installed tasks.org beta, with etesync support. Created a tasklist from tasks.org. If I view it from the etesync android app, it says "Stats loading error", and "Journal is empty (Maybe it's still syncing?)".

The journal looks fine if I retrieve it with the python lib. Tom says "the EteSync Android app doesn't attempt syncing tasks if OpenTasks is not installed, which is obviously not great if you are not using OpenTasks but are using other clients."

**Comment by tasn** [comment] 2020-02-16 16:19
Sorry for not replying before, I was trying to think what is the correct way of handling this.

The thing is: the EteSync app at the moment works as a sync adapter and is based on that. Meaning that it doesn't download anything unless it's syncing it itself, and since OpenTasks is not installed, it's not actually syncing the tasks itself, so it's not downloading anything.
Changing this architecture is a good thing, because we will need that going forward. The problem is that it's a bit of a pain to do. :)

It's something I'll tackle in the next few weeks, maybe next couple of months. I think/hope.

**Comment by uGeek** [comment] 2020-04-02 06:51
Could it be because of the Android version?

I have an android version 9 and the lists are perfectly visible, while another device version 10 does not appear to me.

If I create the list in etesync android, it appears in task.org, but if I create it in task.org, it only appears in android device version 9

**Comment by tasn** [comment] 2020-04-02 08:41
The difference is really just if OpenTasks is installed or not. There's an explicit condition that checks for that and doesn't sync unless it is. So I don't think it has anything to do with the Android version.
With that being said, maybe there's an additional related issue with Android 10, though it's more likely it's just a matter of having OpenTasks installed, vs not.

**Comment by uGeek** [comment] 2020-04-02 14:57
Ok. Thanks
I will continue testing

**Comment by tasn** [comment] 2020-08-07 06:18
Finally fixed now! The fix is not for the underlying problem, but rather for Tasks.org specifically.
Tasks.org now has an OpenTasks compatible interface so we just use that when Tasks.org is installed, and then it shows.

**Closed by tasn** 2020-08-07 06:18 UTC
