### ISSUE TITLE
"calendar sync failed" notification during setup

### ISSUE THREAD

**Issue by dschuermann** [etesync/android#9] opened 2017-04-25 11:08 UTC
During the setup wizard I already got notifications about "calendar sync failed". I took a long time choosing an encryption password :)

**Comment by tasn** [comment] 2017-04-25 12:43
Thanks for reporting. This is very interesting, because before you choose an encryption password, the local account shouldn't even be created, so there should be nothing to sync. I wonder what triggers it.
I'll try to reproduce.

**Comment by dschuermann** [comment] 2017-04-25 12:55
Hmmm, I had the app installed before and re-installed it today. Not sure if this is related.

**Comment by tasn** [comment] 2017-04-25 15:07
Unlikely, because Android wipes app data on uninstall.

**Comment by tasn** [comment] 2017-04-25 15:14
Unfortunately I can't reproduce. :(
I tried a few things, reinstalling a few times, different accounts and it works here in all cases.
Please if you manage to find a reliable way to reproduce it, reopen this ticket and let me know.

Thanks.

**Comment by dschuermann** [comment] 2017-04-25 15:56
Yeah it's just a minor issue.

> Unlikely, because Android wipes app data on uninstall.

I am not sure this is totally true. I think calendars and contacts are not fully wiped. But I don't know right now. Also I don't know about the account.

**Comment by tasn** [comment] 2017-04-25 16:05
I'm not sure what we mean exactly by fully, by I just deleted etesync, and both the accounts, and the calendar data were wiped.

**Comment by dschuermann** [comment] 2017-04-25 16:16
I am just guessing here. I remember that calendars etc are not deleted on uninstall, but maybe I am confusing different situations. See for example http://stackoverflow.com/questions/24288503/deleting-android-calendar-when-app-is-uninstalled

**Comment by tasn** [comment] 2017-04-25 16:24
I stand corrected, and now that you mention that, I do remember seeing it with one of your apps. I got it with offline calendar a while back, and I was genuinely confused. OK, I'll reopen this one and investigate it further in the future.

**Comment by dschuermann** [comment] 2017-04-25 20:34
It has no high priority, just some confusing notifications in a special scenario I think.

**Comment by tasn** [comment] 2017-04-26 09:02
Indeed it isn't, but it's still an issue I'd like to address at some point.

**Comment by tasn** [comment] 2017-05-04 11:30
I think I found the issue, and it should be fixed by:
2e25c44d78cefee613e20f0470731e265806955d

**Closed** 2017-12-03 12:58 UTC

**Comment by tasn** [comment] 2017-12-03 13:00
Glad to hear it now works. :)

**Comment by tasn** [comment] 2017-12-03 13:06
Please let me know if you find it lacking in any way.
